name: deploy-orders

on:
  push:
    branches:
      - master
    paths:
      - "orders/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd orders && docker build -t mendelovic/orders .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push mendelovic/orders
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save 2444a7a5-1b00-4874-90e3-2fb1368d532c
      - name: Restart orders deployment
        run: kubectl rollout restart deployment orders-depl
