name: tests-payments

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: run all tests
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        run: cd payments && npm i && npm run test:ci
