name: tests-payments

on:
  pull_request
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: run all tests
        env:
          STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        run: cd payments && npm i && npm run test:ci
